config/routes.rb
Rails.application.routes.draw do
  root 'home#index'                                                       # Root (Index Page)

  # Dashboard Routes
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'                 # Display Dashboard

  # User Routes
  get 'signup', to: 'users#new', as: 'signup'                             # Display Signup Form
  post 'signup', to: 'users#create'                                       # Process Signup Form

  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'                            # Display Login Form
  post 'login', to: 'sessions#create'                                     # Process Login Form
  get 'logout', to: 'sessions#destroy', as: 'logout'                      # Process Logout

  # Password Reset Routes
  get 'forgot', to: 'password_resets#new', as: 'forgot'                   # Display Forgot Form
  post 'forgot', to: 'password_resets#create'                             # Process Forgot Form
  get 'reset', to: 'password_resets#edit', as: 'reset'                    # Display Reset Form
  post 'reset', to: 'password_resets#edit'                                # Process Reset Form

  # Home Routes
  get 'about', to: 'home#about', as: 'about'                              # About Page
  get 'contact', to: 'home#contact', as: 'contact'                        # Contact Page
  get 'faq', to: 'home#faq', as: 'faq'                                    # FAQ Page
  get 'terms', to: 'home#terms', as: 'terms'                              # Terms Page
  get 'privacy', to: 'home#privacy', as: 'privacy'                        # Privacy Page

  # Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  get 'profile/:id/connections', to: 'profiles#show', as: 'connections'
  get 'profile/:id/connections/received', to: 'profiles#show', as: 'received_requests'
  get 'profile/:id/connections/sent', to: 'profiles#show', as: 'sent_requests'

  # Connection Routes
  get 'profile(/:id/)connect', to: 'friendships#connect', as: 'connect'
  get 'profile(/:id/)cancel', to: 'friendships#cancel', as: 'cancel'
  get 'profile(/:id/)accept', to: 'friendships#accept', as: 'accept'
  get 'profile(/:id/)decline', to: 'friendships#decline', as: 'decline'
  get 'profile(/:id/)disconnect', to: 'friendships#disconnect', as: 'disconnect'

  # Setting Routes
  get 'settings/profile', to: 'profiles#edit', as: 'profile_settings'
  post 'settings/profile', to: 'profiles#update'
  get 'settings/password', to: 'profiles#edit', as: 'password_settings'
  post 'settings/password', to: 'profiles#update'
  get 'settings/account', to: 'profiles#edit', as: 'account_settings'
  post 'settings/account', to: 'profiles#update'

  # Messages Routes
  get 'messages/new', to: 'messages#new', as: 'new_message'

  get 'messages', to: 'messages#index', as: 'message'
  get 'messages/:id', to: 'messages#index', as: 'messages'
  post 'messages/:id', to: 'messages#create'

  # Books Routes
  get 'books', to: 'books#index', as: 'books'

  get 'books/new', to: 'books#new', as: 'new_book'
  post 'books/new', to: 'books#create'

  get 'books/:id', to: 'books#show', as: 'book'

  get 'books/:id/edit', to: 'books#edit', as: 'edit_book'
  post 'books/:id/edit', to: 'books#update'

  get 'books/:id/delete', to: 'books#destroy', as: 'delete_book'

  get 'books/category/:category', to: 'books#index', as: 'books_category'

  get 'books/:id/update', to: 'books#update_date', as: 'update_book_date'

  # Roommates Routes
  get 'roommates', to: 'roommates#index', as: 'roommates'

  get 'roommates/new', to: 'roommates#new', as: 'new_roommate'
  post 'roommates/new', to: 'roommates#create'

  get 'roommates/:id', to: 'roommates#show', as: 'roommate'

  get 'roommates/:id/edit', to: 'roommates#edit', as: 'edit_roommates'
  post 'roommates/:id/edit', to: 'roommates#update'

  get 'roommates/:id/delete', to: 'roommates#destroy', as: 'delete_roommates'

  # get 'roommates/category/:category', to: 'roommates#index', as: 'roommates_category'

  get 'roommates/:id/update', to: 'roommates#update_date', as: 'update_roommates_date'
end

app/models/message.rb
class Message < ActiveRecord::Base
  # ---------------------------------------------------------------------------- #
  # -- Scopes ------------------------------------------------------------------ #
  # ---------------------------------------------------------------------------- #
  scope :all_messages, -> (id, current_user) {where('(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)', id, current_user, current_user, id).order('created_at')}
  scope :all_unread_messages,-> (current_user) {where('(recipient_id = ? AND `read` = 0)', current_user)}
  scope :user_unread_messages,-> (id, current_user) {where('((sender_id = ? AND recipient_id = ?) AND `read` = 0)', id, current_user)}

  # ---------------------------------------------------------------------------- #
  # -- Associations ------------------------------------------------------------ #
  # ---------------------------------------------------------------------------- #

  belongs_to :sender, class_name: 'User', foreign_key: :sender_id
  belongs_to :recipient, class_name: 'User', foreign_key: :recipient_id

  validates_presence_of :sender_id, :recipient_id, :message

  def message_time
    if created_at.to_date == Date.today
      created_at.strftime('%l:%M%P')
    else
      created_at.strftime('%b %d, %l:%M%P')
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :confirm_logged_in

  before_action do
    @conversations = Message.find_by_sql(conversations_query)
    @last_conversation = @conversations.first.correspondent
  end

  def index
    redirect_to messages_path(@last_conversation) unless params[:id]

    if params[:id]
      # && @conversations.include?(params[:id]) TODO: I was doing something important but didn't work! WTF was that?
      @messages = Message.all_messages(params[:id], current_user.id)
      Message.where('recipient_id = ? AND sender_id = ?', current_user.id, params[:id]).update_all(read: true)
    end
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new
    @message.sender_id = current_user.id
    @message.recipient_id = params[:id]
    @message.message = params[:message][:message].strip

    @message.save # TODO: Put if statement. If doesn't save, redirect.
    redirect_to messages_path(params[:id])
  end

  def destroy

  end

  private
  def conversations_query
    "SELECT correspondent, MAX(updated_at) as date FROM
    (SELECT sender_id as correspondent,updated_at FROM messages WHERE recipient_id = #{current_user.id}
    UNION ALL SELECT recipient_id as correspondent, updated_at FROM messages WHERE sender_id = #{current_user.id})
    x GROUP BY correspondent ORDER BY date desc"
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_conversations.html.haml
.section-title-2
  = 'Inbox'
  .section-tools.pull-right{style: 'margin: -1px'}
    = link_to new_message_path, class: 'btn btn-default btn-xs tag-tooltip', data: {toggle: 'tooltip'},
      'data-original-title': 'New Conversation', 'data-placement': 'bottom' do
      %span.glyphicon.btn-glyphicon.glyphicon-pencil
.conversations.list-group
  - @conversations.each do |conversation|
    - user = User.find_by_id(conversation.correspondent)
    - last = Message.all_messages(conversation.correspondent, current_user.id).last
    - total_unread_messages = Message.user_unread_messages(conversation.correspondent, current_user.id).length

    = link_to messages_path(user.id), class: 'conversation list-group-item clearfix' do
      .conversation-photo.pull-left
        = image_tag user.photo.url(:thumb)
      .conversation-details.pull-left
        .conversation-name= "#{user.first_name} #{user.last_name}"
        .conversation-message= last.message
      .conversation-unread.pull-right= total_unread_messages.to_s

app/views/messages/index.html.haml
- user = User.find(params[:id])
-# TODO: Can we put this in model?
- title("Messages | #{user.first_name} #{user.last_name}")
-# TODO: Delete conversation needs to be working!
-# TODO: After some messages, we should be displaying "show older messages" button or auto display when scrolled up.
#left-column
  = render 'messages/conversations'
#right-column
  .section-title-2
    = "#{user.first_name} #{user.last_name}"
    .section-tools.pull-right{style: 'margin: -1px'}
      = link_to '#', class: 'btn btn-default btn-xs tag-tooltip', data: {toggle: 'tooltip'},
        'data-original-title': 'Delete Conversation', 'data-placement': 'bottom' do
        %span.glyphicon.btn-glyphicon.glyphicon-trash
  .messages-container
    .messages-wrapper#messages-wrapper
      - @messages.each do |message|
        - sender = User.find(message.sender_id)
        .message.clearfix
          .message-photo.pull-left
            = image_tag sender.photo.url(:thumb)
          .message-header.pull-left
            .message-name.pull-left
              = link_to "#{sender.first_name} #{sender.last_name}", profile_path(sender.id)
            .message-date.pull-right
              = message.message_time
          .message-body.pull-left
            = message.message
    .message-form-container
      .message-form-wrapper
        = form_for :message, url: messages_path do |f|
          = f.text_area :message, class: 'form-control', placeholder: 'Write a reply...'
          .clearfix= submit_tag 'Reply', class: 'btn btn-primary pull-right'

app/views/messages/new.html.haml
#left-column
  = render 'messages/conversations'
#right-column
  -# TODO: This whole new message system needs to be working.
  .section-title-2
    = 'New Message'
  .messages-container
    .messages-wrapper
      .input-group.recipient_name
        %span.input-group-addon
          %span.glyphicon.glyphicon-user
        %form
          = text_field_tag :recipient_name, nil, class: 'form-control', placeholder: 'Enter Recipient Name'
    .message-form-container
      .message-form-wrapper
        = form_for :message, url: '#' do |f|
          = f.text_area :message, class: 'form-control', placeholder: 'Write a reply...'
          .clearfix= submit_tag 'Send', class: 'btn btn-primary pull-right'