config/routes.rb
Rails.application.routes.draw do
  root 'home#index'                                                       # Root (Index Page)

  # Dashboard Routes
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'                 # Display Dashboard

  # User Routes
  get 'signup', to: 'users#new', as: 'signup'                             # Display Signup Form
  post 'signup', to: 'users#create'                                       # Process Signup Form

  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'                            # Display Login Form
  post 'login', to: 'sessions#create'                                     # Process Login Form
  get 'logout', to: 'sessions#destroy', as: 'logout'                      # Process Logout

  # Password Reset Routes
  get 'forgot', to: 'password_resets#new', as: 'forgot'                   # Display Forgot Form
  post 'forgot', to: 'password_resets#create'                             # Process Forgot Form
  get 'reset', to: 'password_resets#edit', as: 'reset'                    # Display Reset Form
  post 'reset', to: 'password_resets#edit'                                # Process Reset Form

  # Home Routes
  get 'about', to: 'home#about', as: 'about'                              # About Page
  get 'contact', to: 'home#contact', as: 'contact'                        # Contact Page
  get 'faq', to: 'home#faq', as: 'faq'                                    # FAQ Page
  get 'terms', to: 'home#terms', as: 'terms'                              # Terms Page
  get 'privacy', to: 'home#privacy', as: 'privacy'                        # Privacy Page

  # Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  get 'profile/:id/connections', to: 'profiles#show', as: 'connections'
  get 'profile/:id/connections/received', to: 'profiles#show', as: 'received_requests'
  get 'profile/:id/connections/sent', to: 'profiles#show', as: 'sent_requests'

  # Connection Routes
  get 'profile(/:id/)connect', to: 'friendships#connect', as: 'connect'
  get 'profile(/:id/)cancel', to: 'friendships#cancel', as: 'cancel'
  get 'profile(/:id/)accept', to: 'friendships#accept', as: 'accept'
  get 'profile(/:id/)decline', to: 'friendships#decline', as: 'decline'
  get 'profile(/:id/)disconnect', to: 'friendships#disconnect', as: 'disconnect'

  # Setting Routes
  get 'settings/profile', to: 'profiles#edit', as: 'profile_settings'
  post 'settings/profile', to: 'profiles#update'
  get 'settings/password', to: 'profiles#edit', as: 'password_settings'
  post 'settings/password', to: 'profiles#update'
  get 'settings/account', to: 'profiles#edit', as: 'account_settings'
  post 'settings/account', to: 'profiles#update'

  # Messages Routes
  get 'messages/new', to: 'messages#new', as: 'new_message'

  get 'messages', to: 'messages#index', as: 'message'
  get 'messages/:id', to: 'messages#index', as: 'messages'
  post 'messages/:id', to: 'messages#create'

  # Books Routes
  get 'books', to: 'books#index', as: 'books'

  get 'books/new', to: 'books#new', as: 'new_book'
  post 'books/new', to: 'books#create'

  get 'books/:id', to: 'books#show', as: 'book'

  get 'books/:id/edit', to: 'books#edit', as: 'edit_book'
  post 'books/:id/edit', to: 'books#update'

  get 'books/:id/delete', to: 'books#destroy', as: 'delete_book'

  get 'books/category/:category', to: 'books#index', as: 'books_category'

  get 'books/:id/update', to: 'books#update_date', as: 'update_book_date'

  # Roommates Routes
  get 'roommates', to: 'roommates#index', as: 'roommates'

  get 'roommates/new', to: 'roommates#new', as: 'new_roommate'
  post 'roommates/new', to: 'roommates#create'

  get 'roommates/:id', to: 'roommates#show', as: 'roommate'

  get 'roommates/:id/edit', to: 'roommates#edit', as: 'edit_roommates'
  post 'roommates/:id/edit', to: 'roommates#update'

  get 'roommates/:id/delete', to: 'roommates#destroy', as: 'delete_roommates'

  # get 'roommates/category/:category', to: 'roommates#index', as: 'roommates_category'

  get 'roommates/:id/update', to: 'roommates#update_date', as: 'update_roommates_date'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :confirm_logged_in

  def show
    found_user = User.find_by_id(params[:id])

    if found_user
      @profile = found_user
      @friendship = Friendship.find_by_user_id_and_friend_id(current_user.id, @profile.id)
    else
      # render 'errors/profile_not_found'
    end
  end

  def edit
    @profile = User.find_by_id(current_user.id)
  end

  def update
    @profile = User.find_by_id(current_user.id)

    case params[:attribute]
      when 'profile'
        if @profile.update_attributes(profile_parameters)
          flash[:notice] = 'Your profile information has been updated successfully'
          redirect_to request.referrer
        else
          render 'edit'
        end
      when 'photo'
        if params[:button] == 'upload'
          if @profile.update_attributes(photo_parameter)
            flash[:notice] = 'Your profile photo has been updated successfully'
            redirect_to request.referer
          else
            @profile.errors.delete(:photo) # Necessary to prevent duplicate error messages caused by Paperclip
            render 'edit'
          end
        elsif params[:button] == 'delete'
          @profile.photo = nil
          @profile.save
          flash[:notice] = 'Your profile photo has been deleted successfully'
          redirect_to request.referer
        else
          render 'edit'
        end
      when 'username'
        if @profile.update_attributes(username_parameter)
          flash[:notice] = 'Your username has been changed successfully'
          redirect_to request.referrer
        else
          render 'edit'
        end
      when 'email'
        if @profile.update_attributes(email_parameter)
          flash[:notice] = 'Your email has been changed successfully'
          redirect_to request.referrer
        else
          render 'edit'
        end
      when 'password'
        if @profile.change_password(params[:user][:current_password], params[:user][:password], params[:user][:password_confirmation])
          flash[:notice] = 'Your password has been changed successfully'
          redirect_to request.referrer
        else
          render 'edit'
        end
      else
        render 'edit'
    end
  end

  private
  def profile_parameters
    params.require(:user).permit(:first_name, :last_name, :school, :program, :website, :information)
  end

  private
  def username_parameter
    params.require(:user).permit(:username)
  end

  private
  def email_parameter
    params.require(:user).permit(:email)
  end

  private
  def photo_parameter
    params.fetch(:user, {}).permit(:photo)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  # ---------------------------------------------------------------------------- #
  # -- Display Profile Buttons Logic ------------------------------------------- #
  # ---------------------------------------------------------------------------- #
  # The purpose of this helper is to display connection buttons in profile page,
  # right above 'about' section. According to current profile's friendship with
  # current_user, this helper will display proper connection button. Besides,
  # if current_user is in his/her own profile, buttons will not show up.
  #
  # Disconnect button is rendered differently, because it will pop-up bootstrap
  # modal. That's why it is little bit different/
  # ---------------------------------------------------------------------------- #

  def display_profile_buttons
    if @profile.id == current_user.id
      # This is current user's profile, that's why do not display buttons.
    else
      if @friendship.present? # Checking if @friendship has returned nil from profile controller.
        if @friendship.status == 'pending'
          render 'profiles/profile_buttons', locals: {button: 'cancel', path: cancel_path(@profile.id)}
        elsif @friendship.status == 'requested'
          render 'profiles/profile_buttons', locals: {button: 'accept', path: accept_path(@profile.id)}
        elsif @friendship.status == 'accepted'
          render 'profiles/profile_buttons', locals: {button: 'disconnect', path: disconnect_path(@profile.id)}
        else
          render 'profiles/profile_buttons', locals: {button: 'connect', path: connect_path(@profile.id)}
        end
      else
        render 'profiles/profile_buttons', locals: {button: 'connect', path: connect_path(@profile.id)}
      end
    end
  end

  # ---------------------------------------------------------------------------- #
  # -- Display Connections Buttons Logic --------------------------------------- #
  # ---------------------------------------------------------------------------- #
  # The purpose of this helper is to display connection buttons in connections
  # page, right next to connection's name. According to current profile's
  # friendship with current_user, this helper will display proper connection
  # button. Besides, if current_user sees his/her own name, in someone's
  # connections list buttons will not show up.
  # ---------------------------------------------------------------------------- #

  def display_connections_buttons(friend)
    if current_user.friends.include?(friend)
      render 'profiles/connections/connections_buttons', locals: {button: 'dropdown', path: disconnect_path(friend.id), modal_id: friend.id}
    elsif current_user.pending_friends.include?(friend)
      render 'profiles/connections/connections_buttons', locals: {text: 'Cancel', path: cancel_path(friend.id), color: 'btn-info'}
    elsif current_user.requested_friends.include?(friend)
      render 'profiles/connections/connections_buttons', locals: {text: 'Accept', path: accept_path(friend.id), color: 'btn-success'}
    else
      # Don't show any connection button to user itself.
      unless current_user.id == friend.id
        render 'profiles/connections/connections_buttons', locals: {text: 'Connect', path: connect_path(friend.id), color: 'btn-primary'}
      end
    end
  end

  # ---------------------------------------------------------------------------- #
  # -- Display Profile Content Logic ------------------------------------------- #
  # ---------------------------------------------------------------------------- #
  # The purpose of this helper is to display related content on the right side of
  # left profile layout.
  # ---------------------------------------------------------------------------- #

  def display_profile_content
    if current_path?(connections_path)
      render 'profiles/connections/connections'
    elsif current_path?(received_requests_path)
      render 'profiles/connections/received_requests'
    elsif current_path?(sent_requests_path)
      render 'profiles/connections/sent_requests'
    else
      render 'profiles/main'
    end
  end

  # ---------------------------------------------------------------------------- #
  # -- Display Settings Content Logic ------------------------------------------ #
  # ---------------------------------------------------------------------------- #
  # The purpose of this helper is to display related content on the right side of
  # left settings layout.
  # ---------------------------------------------------------------------------- #

  def display_settings_content
    if current_path?(password_settings_path)
      render 'profiles/settings/password'
    elsif current_path?(account_settings_path)
      render 'profiles/settings/account'
    else
      render 'profiles/settings/profile'
    end
  end

  def settings_error_messages_for(object)
    render partial: 'profiles/settings/new_error_messages', locals: {object: object}
  end
end

app/views/profiles/_disconnect_modal.html.haml
.modal.fade{ id: "disconnect-modal#{locals[:modal_id]}" }
  .modal-dialog
    .modal-content
      .modal-header
        %button{ type: 'button', class: 'close', 'data-dismiss': 'modal', 'aria-label': 'Close' }
          %span{ 'aria-hidden': 'true' } &times;
        %h4.modal-title= 'Are you sure?'
      .modal-body
        You are about to disconnect from this person. Would you like to continue?
      .modal-footer
        %button{ type: 'button', class: 'btn btn-default', 'data-dismiss': 'modal' }= 'Cancel'
        = link_to 'Disconnect', locals[:path], class: 'btn btn-danger'

app/views/profiles/_profile_buttons.html.haml
= render 'profiles/disconnect_modal', locals: {path: locals[:path], modal_id: ''}

.profile-buttons
  - if locals[:button] == 'disconnect'
    = link_to 'Disconnect', '#disconnect-modal', 'data-toggle': 'modal', class: 'btn btn-danger profile-button-size'
  - elsif locals[:button] == 'accept'
    = link_to 'Accept Request', accept_path(@profile.id), class: 'btn btn-success profile-button-size'
    = link_to 'Decline Request', decline_path(@profile.id), class: 'btn btn-warning profile-button-size'
  - elsif locals[:button] == 'cancel'
    = link_to 'Cancel Request', cancel_path(@profile.id), class: 'btn btn-info profile-button-size'
  - else
    = link_to 'Connect', connect_path(@profile.id), class: 'btn btn-primary profile-button-size'

  = link_to 'Send Message', '#', class: 'btn btn-default profile-button-size'

app/views/profiles/edit.html.haml
= settings_error_messages_for(@profile)

- if flash[:notice].present?
  .alert.alert-success{ role: 'alert', style:'margin-bottom: 20px' }
    .alert-title= 'Success'
    = flash[:notice].html_safe

#left-column
  .list-group
    .section-title-2= 'Personal Settings'
    = active_link_to profile_settings_path, class: 'list-group-item' do
      .clearfix
        .pull-left= 'Profile'
        .pull-right
          %span.glyphicon.glyphicon-user
    = active_link_to password_settings_path, class: 'list-group-item' do
      .clearfix
        .pull-left= 'Password'
        .pull-right
          %span.glyphpro.glyphpro-keys
    = active_link_to account_settings_path, class: 'list-group-item' do
      .clearfix
        .pull-left= 'Account'
        .pull-right
          %span.glyphpro.glyphpro-settings

#right-column
  = display_settings_content

app/views/profiles/show.html.haml
#left-column
  .section-container
    .profile-photo= image_tag @profile.photo.url(:profile)

    .profile-name= link_to "#{@profile.first_name} #{@profile.last_name}", profile_path(@profile.id)

    - unless @profile.information.blank?
      .profile-info= @profile.information

    .profile-stats.clearfix
      .profile-stat.pull-left
        = link_to connections_path(@profile.id), { class: 'btn btn-default' } do
          %strong= @profile.friends.size
          %span= 'Connections'
      .profile-stat.pull-right
        = link_to '#', { class: 'btn btn-default' } do
          %strong= 0
          %span= 'Courses'

  .profile-buttons-container
    = display_profile_buttons

  .section-container
    .section-header
      .section-title= 'About'

    - unless @profile.school.blank?
      .profile-about-item
        %span.glyphicon.glyphicon-education.icon-spacer
        = @profile.school

    - unless @profile.program.blank?
      .profile-about-item
        %span.glyphicon.glyphicon-blackboard.icon-spacer
        = @profile.program

    .profile-about-item
      %span.glyphicon.glyphicon-envelope.icon-spacer
      = @profile.email

    - unless @profile.website.blank?
      .profile-about-item
        %span.glyphicon.glyphicon-link.icon-spacer
        = @profile.website

    .profile-about-item
      %span.glyphicon.glyphicon-calendar.icon-spacer
      = "Joined on #{@profile.join_date}"

#right-column
  = display_profile_content