config/routes.rb
Rails.application.routes.draw do
  root 'home#index'                                                       # Root (Index Page)

  # Dashboard Routes
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'                 # Display Dashboard

  # User Routes
  get 'signup', to: 'users#new', as: 'signup'                             # Display Signup Form
  post 'signup', to: 'users#create'                                       # Process Signup Form

  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'                            # Display Login Form
  post 'login', to: 'sessions#create'                                     # Process Login Form
  get 'logout', to: 'sessions#destroy', as: 'logout'                      # Process Logout

  # Password Reset Routes
  get 'forgot', to: 'password_resets#new', as: 'forgot'                   # Display Forgot Form
  post 'forgot', to: 'password_resets#create'                             # Process Forgot Form
  get 'reset', to: 'password_resets#edit', as: 'reset'                    # Display Reset Form
  post 'reset', to: 'password_resets#edit'                                # Process Reset Form

  # Home Routes
  get 'about', to: 'home#about', as: 'about'                              # About Page
  get 'contact', to: 'home#contact', as: 'contact'                        # Contact Page
  get 'faq', to: 'home#faq', as: 'faq'                                    # FAQ Page
  get 'terms', to: 'home#terms', as: 'terms'                              # Terms Page
  get 'privacy', to: 'home#privacy', as: 'privacy'                        # Privacy Page

  # Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  get 'profile/:id/connections', to: 'profiles#show', as: 'connections'
  get 'profile/:id/connections/received', to: 'profiles#show', as: 'received_requests'
  get 'profile/:id/connections/sent', to: 'profiles#show', as: 'sent_requests'

  # Connection Routes
  get 'profile(/:id/)connect', to: 'friendships#connect', as: 'connect'
  get 'profile(/:id/)cancel', to: 'friendships#cancel', as: 'cancel'
  get 'profile(/:id/)accept', to: 'friendships#accept', as: 'accept'
  get 'profile(/:id/)decline', to: 'friendships#decline', as: 'decline'
  get 'profile(/:id/)disconnect', to: 'friendships#disconnect', as: 'disconnect'

  # Setting Routes
  get 'settings/profile', to: 'profiles#edit', as: 'profile_settings'
  post 'settings/profile', to: 'profiles#update'
  get 'settings/password', to: 'profiles#edit', as: 'password_settings'
  post 'settings/password', to: 'profiles#update'
  get 'settings/account', to: 'profiles#edit', as: 'account_settings'
  post 'settings/account', to: 'profiles#update'

  # Messages Routes
  get 'messages/new', to: 'messages#new', as: 'new_message'

  get 'messages', to: 'messages#index', as: 'message'
  get 'messages/:id', to: 'messages#index', as: 'messages'
  post 'messages/:id', to: 'messages#create'

  # Books Routes
  get 'books', to: 'books#index', as: 'books'

  get 'books/new', to: 'books#new', as: 'new_book'
  post 'books/new', to: 'books#create'

  get 'books/:id', to: 'books#show', as: 'book'

  get 'books/:id/edit', to: 'books#edit', as: 'edit_book'
  post 'books/:id/edit', to: 'books#update'

  get 'books/:id/delete', to: 'books#destroy', as: 'delete_book'

  get 'books/category/:category', to: 'books#index', as: 'books_category'

  get 'books/:id/update', to: 'books#update_date', as: 'update_book_date'

  # Roommates Routes
  get 'roommates', to: 'roommates#index', as: 'roommates'

  get 'roommates/new', to: 'roommates#new', as: 'new_roommate'
  post 'roommates/new', to: 'roommates#create'

  get 'roommates/:id', to: 'roommates#show', as: 'roommate'

  get 'roommates/:id/edit', to: 'roommates#edit', as: 'edit_roommates'
  post 'roommates/:id/edit', to: 'roommates#update'

  get 'roommates/:id/delete', to: 'roommates#destroy', as: 'delete_roommates'

  # get 'roommates/category/:category', to: 'roommates#index', as: 'roommates_category'

  get 'roommates/:id/update', to: 'roommates#update_date', as: 'update_roommates_date'
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :seller, class_name: 'User', foreign_key: :seller_id

  # ---------------------------------------------------------------------------- #
  # -- Validation Logic -------------------------------------------------------- #
  # ---------------------------------------------------------------------------- #

  # -- Title ------------------------------------------------------------------- #
  validates :title,
            presence: {message: 'Title cannot be blank'},
            length: {within: 6..100, message: 'Title length should be within 6 to 100 characters'}

  # -- Description ------------------------------------------------------------- #
  validates :description,
            presence: {message: 'Description cannot be blank'},
            length: {minimum: 10, message: 'Description length should be minimum 10 characters'}

  # -- Category ---------------------------------------------------------------- #
  validates :category,
            presence: {message: 'Please choose a category for your ad'}

  # -- Price ------------------------------------------------------------------- #
  validates :price,
            presence: {message: 'Price cannot be blank'},
            length: {maximum: 8, message: 'Price cannot be higher than 99,999.99'}

  # ---------------------------------------------------------------------------- #
  # -- Paperclip --------------------------------------------------------------- #
  # ---------------------------------------------------------------------------- #

  has_attached_file :photo, styles: { book: '210x', thumb: '100x100#' }, default_url: '/missing_book_photo.png'

  validates_attachment :photo,
                       content_type: {content_type: ['image/jpeg', 'image/png'], message: 'Please upload a photo with jpeg and png extensions only'},
                       size: {less_than: 2.megabytes, message: 'The size of photo should be less than 2 megabytes'}

  def book_time
    if updated_at.to_date == Date.today
      updated_at.strftime('Today, %l:%M%P')
    elsif updated_at.to_date == Date.yesterday
      updated_at.strftime('Yesterday, %l:%M%P')
    else
      updated_at.strftime('%b %d, %l:%M%P')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :confirm_logged_in

  def index
    case params[:category]
      when 'biographies'
        @books = Book.where(category: 'Biographies').order('updated_at desc')
      when 'children-s-books'
        @books = Book.where(category: 'Children\'s Books').order('updated_at desc')
      when 'comics-and-graphic-novels'
        @books = Book.where(category: 'Comics & Graphic Novels').order('updated_at desc')
      when 'literature-and-fiction'
        @books = Book.where(category: 'Literature & Fiction').order('updated_at desc')
      when 'magazines'
        @books = Book.where(category: 'Magazines').order('updated_at desc')
      when 'textbooks'
        @books = Book.where(category: 'Textbooks').order('updated_at desc')
      when 'young-adult'
        @books = Book.where(category: 'Young Adult').order('updated_at desc')
      when 'other'
        @books = Book.where(category: 'Other').order('updated_at desc')
      else
        @books = Book.order('updated_at desc')
    end

    @my_books = Book.where(seller_id: current_user.id).order('updated_at desc')
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_parameters)
    @book.seller_id = current_user.id

    if @book.save
      flash[:notice] = 'Your book ad has been created successfully'
      redirect_to book_path(@book.id) # Redirect to created ad's page.
    else
      @book.errors.delete(:photo) # Necessary to prevent duplicate error messages caused by Paperclip
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_parameters)
      redirect_to book_path(@book.id) # Redirect to updated ad's page.
    else
      @book.errors.delete(:photo) # Necessary to prevent duplicate error messages caused by Paperclip
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])

    # TODO: You should be able to delete your own ad only. FIX.
    # if @book.friends.include?(@friend)
    #   @book.destroy
    # end

    redirect_to request.referrer
  end

  def update_date
    @book = Book.find(params[:id])
    @book.updated_at = Time.now

    # cookies.delete(:book_update_date)
    # Setting up cookie for each book ads for user.
    cookie_name = 'book_update_date' + params[:id]
    if !cookies[cookie_name]
      cookies[cookie_name] = {
          value: Time.now,
          expires: 5.hours.from_now
      }
      if @book.save
        flash[:success] = 'Your post has been reposted'
      else
        redirect_to request.referrer
      end
    else
      flash[:error] = 'You can only repost each of your ads every 5 hours'
      # TODO: Find a way to print count down from 5 hours, in the error.
      # puts Time.now - cookies[cookie_name].to_i
    end

    redirect_to request.referrer
  end

  private
  def book_parameters
    params.require(:book).permit(:title, :description, :category, :price, :photo)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def options_for_categories
    ['Biographies',
     'Children\'s Books',
     'Comics & Graphic Novels',
     'Literature & Fiction',
     'Magazines',
     'Textbooks',
     'Young Adult',
     'Other']
  end

  def books_error_messages_for(object)
    render partial: 'books/error_messages', locals: {object: object}
  end
end

app/views/books/_delete_ad_modal.html.haml
.modal.fade{ id: "delete-ad-modal#{locals[:modal_id]}" }
  .modal-dialog
    .modal-content
      .modal-header
        %button{ type: 'button', class: 'close', 'data-dismiss': 'modal', 'aria-label': 'Close' }
          %span{ 'aria-hidden': 'true' } &times;
        %h4.modal-title= 'Are you sure?'
      .modal-body
        You are about to delete this ad. This action cannot be reversed. Would you like to continue?
      .modal-footer
        %button{ type: 'button', class: 'btn btn-default', 'data-dismiss': 'modal' }= 'Cancel'
        = link_to 'Delete', locals[:path], class: 'btn btn-danger'

app/views/books/_error_messages.html.haml
- if object && object.errors.size > 0
  .alert.alert-danger{ role: 'alert', style: 'margin-bottom: 20px;'}
    .alert-title= 'Save could not be completed'
    %ul
      - @book.errors.each do |attr, msg|
        - if @book.errors[attr].first == msg
          = "<li>#{msg}</li>".html_safe

app/views/books/_form.html.haml
%table.horizontal-form
  %col{span: 1, style: 'width: 114px'}
  %col{span: 1, style: 'width: 425px'}
  %tr
    %td
      = f.label :photo, 'Book Photo'
    %td
      .input-group.form-control-md
        %span.input-group-btn
          %span.btn.btn-primary.btn-file
            %span.glyphicon.glyphicon-camera{style: 'color: white'} #{f.file_field :photo}
        %input.form-control{readonly: '', type: 'text'}
  %tr
    %td
      = f.label :category, 'Category'
    %td
      = f.select :category, options_for_categories, {prompt: 'Select a Category'}, {class: 'form-control select-book-category form-control-md'}
  %tr
    %td
      = f.label :price, 'Price'
    %td
      .input-group.form-control-md
        .input-group-addon= '$'
        = f.text_field :price, class: 'form-control', placeholder: '0.00', data: {autonumeric: {vMax: '99999.99'}}
  %tr
    %td
      = f.label :title, 'Ad Title'
    %td
      = f.text_field :title, class: 'form-control form-control-lg', placeholder: 'Ad Title'

.mt10
  = f.text_area :description, id: 'book-description'
  -# TODO: There is a problem with problem. Do copy-paste. Because of p tag.

.mt10{style: 'margin-left: 208px;'}
  = button_tag type: 'submit', class: 'btn btn-success' do
    %span.glyphicon.glyphicon-send.icon-spacer
    Post It

app/views/books/_sidebar.html.haml
= form_tag do # TODO: form_tag search_path do
  .input-group.books-search
    = search_field_tag :search, nil, class: 'form-control', placeholder: 'Search in Ads'
    .input-group-btn
      %button.btn.btn-default
        %span.glyphicon.glyphicon-search

  = link_to new_book_path, class: 'btn btn-default post-ad-button' do
    %span.glyphicon.glyphicon-bullhorn.icon-spacer
    = 'Post an Book Ad'

  .list-group
    .section-title-2
      %span.glyphpro.glyphpro-list-alt
      = 'Categories'
    = active_link_to books_path, class: 'list-group-item' do
      = 'All'
    = active_link_to books_category_path('biographies'), class: 'list-group-item' do
      = 'Biographies'
    = active_link_to books_category_path('children-s-books'), class: 'list-group-item' do
      = 'Children\'s Books'
    = active_link_to books_category_path('comics-and-graphic-novels'), class: 'list-group-item' do
      = 'Comics & Graphic Novels'
    = active_link_to books_category_path('literature-and-fiction'), class: 'list-group-item' do
      = 'Literature & Fiction'
    = active_link_to books_category_path('magazines'), class: 'list-group-item' do
      = 'Magazines'
    = active_link_to books_category_path('textbooks'), class: 'list-group-item' do
      = 'Textbooks'
    = active_link_to books_category_path('young-adult'), class: 'list-group-item' do
      = 'Young Adult'
    = active_link_to books_category_path('other'), class: 'list-group-item' do
      = 'Other'

app/views/books/edit.html.haml
- title("Edit | #{@book.title}")

= books_error_messages_for(@book)

#left-column
  = render 'books/sidebar'
#right-column
  .section-container
    .section-header
      .section-title= 'Edit This Book Ad'
    = form_for :book, html: {multipart: true}, url: edit_book_path do |f|
      = hidden_field_tag 'attribute', 'photo', id: nil
      = render partial: 'books/form', locals: {f: f}

app/views/books/index.html.haml
- title('Book Ads')
-# TODO: Add Title with categories as well, like "Book Ads | Biographies"

- if flash[:error].present?
  .alert.alert-danger{ role: 'alert', style:'margin-bottom: 20px' }
    .alert-title= 'Error'
    = flash[:error].html_safe

- if flash[:success].present?
  .alert.alert-success{ role: 'alert', style:'margin-bottom: 20px' }
    .alert-title= 'Success'
    = flash[:success].html_safe
#left-column
  = render 'books/sidebar'
#right-column
  - if @my_books.length > 0
    .section-title-2= 'My Book Ads'
    %table.table.table-striped.my-book-ads
      %tr
        %th{style: 'width: 97px'}= 'Actions'
        %th= 'Title'
        %th{style: 'width: 150px'}= 'Posted On'
        %th{style: 'width: 100px'}= 'Price'
      - @my_books.each do |my_book|
        = render 'books/delete_ad_modal', locals: { path: delete_book_path(my_book.id), modal_id: my_book.id }
        %tr
          %td
            = link_to update_book_date_path(my_book.id), class: 'btn btn-default btn-xs tag-tooltip', 'data-toggle': 'modal',
              'data-original-title': 'Repost', 'data-placement': 'bottom' do
              %span.glyphicon.glyphicon-refresh
            = link_to edit_book_path(my_book.id), class: 'btn btn-default btn-xs tag-tooltip', 'data-toggle': 'modal',
              'data-original-title': 'Edit', 'data-placement': 'bottom' do
              %span.glyphicon.glyphicon-edit
            = link_to "#delete-ad-modal#{my_book.id}", class: 'btn btn-default btn-xs tag-tooltip', 'data-toggle': 'modal',
              'data-original-title': 'Delete', 'data-placement': 'bottom' do
              %span.glyphicon.glyphicon-trash
          %td.my-ads-title
            = link_to my_book.title, book_path(my_book.id)
          %td
            = my_book.book_time
          %td
            - if my_book.price == '0'
              = 'Free'
            - else
              = number_to_currency(my_book.price)
  .section-title-2= 'Book Ads'
  .section-container-2.clearfix
    - if @books.length > 0
      - @books.each do |book|
        .book-ad.clearfix
          .book-photo.pull-left= image_tag book.photo.url(:thumb)
          .book-info.pull-left
            .book-title= link_to book.title, book_path(book.id)
            .book-time= "#{book.book_time} | #{book.category}"
            .book-description= truncate(strip_tags(book.description), length: 150)
          .book-price.pull-right
            - if book.price == '0'
              = 'Free'
            - else
              = number_to_currency(book.price)
    - else
      Unfortunately there is no any book ad to display in the selected category.

  -# TODO: Add pagination.

app/views/books/new.html.haml
- title('Post a New Book Ad')

= books_error_messages_for(@book)

#left-column
  = render 'books/sidebar'
#right-column
  .section-container
    .section-header
      .section-title= 'Post a New Ad for Your Book'
    = form_for :book, html: {multipart: true}, url: new_book_path do |f|
      = hidden_field_tag 'attribute', 'photo', id: nil
      = render partial: 'books/form', locals: {f: f}

app/views/books/show.html.haml
- title("#{@book.title}")

- user = User.find_by_id(@book.seller_id)

= render 'books/delete_ad_modal', locals: { path: delete_book_path(@book.id), modal_id: '' }

- if flash[:notice].present?
  .alert.alert-success{ role: 'alert', style:'margin-bottom: 20px' }
    .alert-title= 'Success'
    = flash[:notice].html_safe
#left-column
  = render 'books/sidebar'
#right-column
  .section-container.clearfix
    .section-header
      .section-title= @book.title
    .book-ad-column.pull-left
      .book-ad-photo= image_tag @book.photo.url(:book)
      - if @book.seller_id == current_user.id
        .book-ad-buttons
          = link_to 'Edit This Ad', edit_book_path(@book.id), class: 'btn btn-info button-ad-button-size'
          = link_to 'Delete This Ad', '#delete-ad-modal', 'data-toggle': 'modal', class: 'btn btn-danger button-ad-button-size'
      .book-ad-details
        .book-ad-item
          %span.glyphicon.glyphicon-user.icon-spacer
          = link_to "#{user.first_name} #{user.last_name}", profile_path(user.id)
        .book-ad-item
          %span.glyphicon.glyphicon-calendar.icon-spacer
          = @book.book_time
        .book-ad-item
          %span.glyphicon.glyphicon-usd.icon-spacer
          %span.book-ad-price
            - if @book.price == '0'
              = 'Free'
            - else
              = number_to_currency(@book.price, unit: '')
        .book-ad-item
          %span.glyphicon.glyphicon-book.icon-spacer
          = @book.category
    .book-ad-description.pull-right= @book.description.html_safe