config/routes.rb
Rails.application.routes.draw do
  root 'home#index'                                                       # Root (Index Page)

  # Dashboard Routes
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'                 # Display Dashboard

  # User Routes
  get 'signup', to: 'users#new', as: 'signup'                             # Display Signup Form
  post 'signup', to: 'users#create'                                       # Process Signup Form

  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'                            # Display Login Form
  post 'login', to: 'sessions#create'                                     # Process Login Form
  get 'logout', to: 'sessions#destroy', as: 'logout'                      # Process Logout

  # Password Reset Routes
  get 'forgot', to: 'password_resets#new', as: 'forgot'                   # Display Forgot Form
  post 'forgot', to: 'password_resets#create'                             # Process Forgot Form
  get 'reset', to: 'password_resets#edit', as: 'reset'                    # Display Reset Form
  post 'reset', to: 'password_resets#edit'                                # Process Reset Form

  # Home Routes
  get 'about', to: 'home#about', as: 'about'                              # About Page
  get 'contact', to: 'home#contact', as: 'contact'                        # Contact Page
  get 'faq', to: 'home#faq', as: 'faq'                                    # FAQ Page
  get 'terms', to: 'home#terms', as: 'terms'                              # Terms Page
  get 'privacy', to: 'home#privacy', as: 'privacy'                        # Privacy Page

  # Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  get 'profile/:id/connections', to: 'profiles#show', as: 'connections'
  get 'profile/:id/connections/received', to: 'profiles#show', as: 'received_requests'
  get 'profile/:id/connections/sent', to: 'profiles#show', as: 'sent_requests'

  # Connection Routes
  get 'profile(/:id/)connect', to: 'friendships#connect', as: 'connect'
  get 'profile(/:id/)cancel', to: 'friendships#cancel', as: 'cancel'
  get 'profile(/:id/)accept', to: 'friendships#accept', as: 'accept'
  get 'profile(/:id/)decline', to: 'friendships#decline', as: 'decline'
  get 'profile(/:id/)disconnect', to: 'friendships#disconnect', as: 'disconnect'

  # Setting Routes
  get 'settings/profile', to: 'profiles#edit', as: 'profile_settings'
  post 'settings/profile', to: 'profiles#update'
  get 'settings/password', to: 'profiles#edit', as: 'password_settings'
  post 'settings/password', to: 'profiles#update'
  get 'settings/account', to: 'profiles#edit', as: 'account_settings'
  post 'settings/account', to: 'profiles#update'

  # Messages Routes
  get 'messages/new', to: 'messages#new', as: 'new_message'

  get 'messages', to: 'messages#index', as: 'message'
  get 'messages/:id', to: 'messages#index', as: 'messages'
  post 'messages/:id', to: 'messages#create'

  # Books Routes
  get 'books', to: 'books#index', as: 'books'

  get 'books/new', to: 'books#new', as: 'new_book'
  post 'books/new', to: 'books#create'

  get 'books/:id', to: 'books#show', as: 'book'

  get 'books/:id/edit', to: 'books#edit', as: 'edit_book'
  post 'books/:id/edit', to: 'books#update'

  get 'books/:id/delete', to: 'books#destroy', as: 'delete_book'

  get 'books/category/:category', to: 'books#index', as: 'books_category'

  get 'books/:id/update', to: 'books#update_date', as: 'update_book_date'

  # Roommates Routes
  get 'roommates', to: 'roommates#index', as: 'roommates'

  get 'roommates/new', to: 'roommates#new', as: 'new_roommate'
  post 'roommates/new', to: 'roommates#create'

  get 'roommates/:id', to: 'roommates#show', as: 'roommate'

  get 'roommates/:id/edit', to: 'roommates#edit', as: 'edit_roommates'
  post 'roommates/:id/edit', to: 'roommates#update'

  get 'roommates/:id/delete', to: 'roommates#destroy', as: 'delete_roommates'

  # get 'roommates/category/:category', to: 'roommates#index', as: 'roommates_category'

  get 'roommates/:id/update', to: 'roommates#update_date', as: 'update_roommates_date'
end

app/views/layouts/_footer.html.haml
%span= link_to 'About', about_path
%span= link_to 'Contact Us', contact_path
%span= link_to 'FAQ', faq_path
%span= link_to 'Terms of Service', terms_path
%span= link_to 'Privacy Policy', privacy_path
%span= link_to 'Sign up', signup_path
%span= link_to 'Log In', login_path
%br
Student Valley &copy;2015 - Version 0.3.0
%br
a Cagdas Yonder production

app/views/layouts/application.html.haml
!!! 5
%html
  %head
  %title= yield(:title).presence || 'Student Valley'
  %meta{ charset: 'utf-8' }
  %meta{ name: 'viewport', content:'width=device-width, initial-scale=1' }
  %meta{ 'http-equiv': 'x-ua-compatible', content: 'ie=edge' }
  = stylesheet_link_tag 'application', 'data-turbolinks-track': true
  = javascript_include_tag 'application', 'data-turbolinks-track': true
  = csrf_meta_tag
  %body
    #container
      %header.clearfix
        #header-wrapper
          #logo.text-hide.pull-left
            = link_to 'Student Valley', root_path, title: 'Go to Student Valley'
          .pull-left
            = form_tag do # TODO: form_tag search_path do
              .input-group#header-search
                = search_field_tag :search, nil, class: 'form-control', placeholder: 'Search in Student Valley'
                .input-group-btn
                  %button.btn.btn-default
                    %span.glyphicon.glyphicon-search
          #navigation.pull-right
            = link_to dashboard_path, class: 'btn btn-default tag-tooltip', data: {toggle: 'tooltip'},
            'data-original-title': 'Dashboard', 'data-placement': 'bottom' do
              %span.glyphicon.glyphicon-home

            - notification = 'notification' if received_messages > 0

            = link_to message_path, class: "btn btn-default #{notification} tag-tooltip", data: {toggle: 'tooltip'},
            'data-original-title': 'Messages', 'data-placement': 'bottom', 'data-badge': received_messages do
              %span.glyphicon.glyphicon-inbox

            .btn-group
              %button.btn.btn-default.dropdown-toggle{ type: 'button', 'data-toggle': 'dropdown',
              'aria-haspopup': 'true', 'aria-expanded': 'true'}
                Courses
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'OOP345', '#'
                %li= link_to 'DBS301', '#'
                %li= link_to 'CUL710', '#'
                %li= link_to 'INT322', '#'

            .btn-group
              = link_to 'Profile', profile_path(current_user.id), class: 'btn btn-default'
              %button.btn.btn-default.dropdown-toggle{ 'data-toggle': 'dropdown',
              'aria-haspopup': 'true', 'aria-expanded': 'false' }
                %span.caret
                %span.sr-only= 'Toggle Dropdown'
              %ul.dropdown-menu
                %li
                  = link_to connections_path(current_user.id) do
                    %span.glyphpro.glyphpro-user_group.icon-spacer
                    My Connections
                %li
                  = link_to '#' do
                    %span.glyphicon.glyphicon-briefcase.icon-spacer
                    My Groups
                %li.divider{ role: 'separator' }
                %li= link_to 'Add Courses', '#'
                %li= link_to 'Join Groups', '#'
                %li= link_to 'Find Books', books_path
                %li= link_to 'Find Roommates', roommates_path
                %li.divider{ role: 'separator' }
                %li
                  = link_to profile_settings_path do
                    %span.glyphicon.glyphicon-cog.icon-spacer
                    Settings
                %li
                  = link_to logout_path do
                    %span.glyphpro.glyphpro-power.icon-spacer
                    Log Out
      #body.clearfix
        = yield
  %footer
    = render partial: 'layouts/footer'

app/views/layouts/home.html.haml
!!! 5
%html
  %head
  %title= yield(:title).presence || 'Student Valley'
  %meta{ charset: 'utf-8' }
  %meta{ name: 'viewport', content:'width=device-width, initial-scale=1' }
  %meta{ 'http-equiv': 'x-ua-compatible', content: 'ie=edge' }
  = stylesheet_link_tag 'home', 'data-turbolinks-track': true
  = javascript_include_tag 'home', 'data-turbolinks-track': true
  = csrf_meta_tag
  %body
    #background
      #container
        %header.clearfix
          #logo.text-hide.pull-left
            = link_to 'Student Valley', root_path, title: 'Go to Student Valley'
          - if current_path?(root_path)
            #login.pull-right
              = form_tag login_path do
                %table
                  %tr
                    %td
                      = label_tag :login_id, 'Email or Username', class: 'sr-only'
                      = text_field_tag :login_id, nil, class: 'form-control form-control-sm', placeholder:'Email or Username'
                    %td
                      = label_tag :password, 'Password', class: 'sr-only'
                      = password_field_tag :password, nil, class: 'form-control form-control-sm', placeholder: 'Password'
                    %td= submit_tag 'Log In', class: 'btn btn-primary'
                  %tr
                    %td.checkbox
                      = label_tag :remember_me do
                        = check_box_tag :remember_me
                        = 'Remember me'
                    %td= link_to 'Forgot your password?', forgot_path
          - elsif current_path?(login_path)
            .buttons.pull-right
              =link_to 'Go to <br/ >Sign Up'.html_safe, signup_path, class: 'btn btn-primary'
          - elsif current_path?(signup_path)
            .buttons.pull-right
              =link_to 'Go to <br/ >Log In'.html_safe, login_path, class: 'btn btn-primary'
          - elsif cookies[:authorization_token]
            .home-panel.pull-right
              .home-panel-text= 'You are logged in as:'
              .pull-left
                = image_tag current_user.photo.url(:thumb)
              .panel-wrapper.clearfix
                .home-panel-info.pull-left
                  = link_to "#{current_user.first_name} #{current_user.last_name}", profile_path(current_user.id)
                .home-panel-info.pull-left
                  = current_user.school
          - else
            .buttons.pull-right
              =link_to 'Go to <br/ >Sign Up'.html_safe, signup_path, class: 'btn btn-primary'
              =link_to 'Go to <br/ >Log In'.html_safe, login_path, class: 'btn btn-primary'
        #body.clearfix{ style: body_width }
          = yield
  %footer
    = render partial: 'layouts/footer'